export const sampleTickets = [
  {
    id: 'ticket-1',
    title: 'Cannot access email',
    category: 'Email',
    priority: 'HIGH',
    status: 'OPEN',
    createdBy: 'ferran@example.com',
    createdAt: '2026-07-09',
    description: 'The user cannot sign in to the company email account after resetting the password.',
  },
  {
    id: 'ticket-2',
    title: 'Laptop running very slowly',
    category: 'Hardware',
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    createdBy: 'amira@example.com',
    createdAt: '2026-07-10',
    description: 'The laptop takes several minutes to start and applications frequently stop responding.',
  },
  {
    id: 'ticket-3',
    title: 'VPN disconnects repeatedly',
    category: 'Network',
    priority: 'HIGH',
    status: 'OPEN',
    createdBy: 'marcus@example.com',
    createdAt: '2026-07-11',
    description: 'The remote connection drops every few minutes while the user is working from home.',
  },
  {
    id: 'ticket-4',
    title: 'Install design software',
    category: 'Software',
    priority: 'LOW',
    status: 'RESOLVED',
    createdBy: 'sofia@example.com',
    createdAt: '2026-07-12',
    description: 'The requested design application was approved and installed on the user’s workstation.',
  },
  {
    id: 'ticket-5',
    title: 'Printer is not responding',
    category: 'Hardware',
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    createdBy: 'daniel@example.com',
    createdAt: '2026-07-13',
    description: 'The shared printer appears offline even though its power and network lights are on.',
  },
  {
    id: 'ticket-6',
    title: 'Reset account password',
    category: 'Account',
    priority: 'LOW',
    status: 'RESOLVED',
    createdBy: 'mei@example.com',
    createdAt: '2026-07-14',
    description: 'The user requested a password reset after being locked out of the support portal.',
  },
]
