### Health check
GET http://localhost:8080/api/health


### Get all assets
GET http://localhost:8080/api/assets


### Filter assets by status
GET http://localhost:8080/api/assets?status=AVAILABLE


### Filter assets by category
GET http://localhost:8080/api/assets?category=Laptop


### Filter assets by location
GET http://localhost:8080/api/assets?location=HQ


### Get paged assets
GET http://localhost:8080/api/assets/paged?page=0&size=5


### Get paged assets sorted by name ascending
GET http://localhost:8080/api/assets/paged?page=0&size=5&sortBy=name&direction=asc


### Get paged assets sorted by assetTag descending
GET http://localhost:8080/api/assets/paged?page=0&size=5&sortBy=assetTag&direction=desc


### Create valid asset
POST http://localhost:8080/api/assets
Content-Type: application/json

{
  "assetTag": "CAM-2026-1001",
  "name": "Logitech Webcam",
  "category": "Camera",
  "serialNumber": "SN-CAM-1001",
  "location": "HQ Level 2"
}


### Create duplicate asset tag - should return 409 Conflict
POST http://localhost:8080/api/assets
Content-Type: application/json

{
  "assetTag": "CAM-2026-1001",
  "name": "Duplicate Webcam",
  "category": "Camera",
  "serialNumber": "SN-CAM-2002",
  "location": "HQ Level 2"
}


### Create duplicate serial number - should return 409 Conflict
POST http://localhost:8080/api/assets
Content-Type: application/json

{
  "assetTag": "CAM-2026-3003",
  "name": "Another Webcam",
  "category": "Camera",
  "serialNumber": "SN-CAM-1001",
  "location": "HQ Level 2"
}

### Register
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "test@example.com",
  "password": "Password123!"
}

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password123!"
}

### Login with invalid credentials - should return 401 Unauthorized
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password12!"
}
